hace que hasnext() devuelva false . se vuelve a iniciar el subproceso 1, pensando que hasnext() sigue siendo true , y después invoca next() . aunque los métodos concretos están sincronizados, el cliente usa dos métodos. es un problema real y un ejemplo que puede surgir en código concurrente. en este caso concreto, el problema es especialmente sutil ya que la única ocasión en la que produce un fallo es durante la iteración final del iterador. si los subprocesos se dividen de forma correcta, puede que uno supere el final del iterador. es el tipo de error que surge en un sistema que lleva tiempo en producción, y es difícil de detectar. tiene tres opciones: tolerar el fallo. solucionar el problema cambiando el cliente: bloqueo basado en el cliente. solucionar el problema cambiando el servidor, lo que también provoca que cambie el cliente: bloqueo basado en el servidor. tolerar el fallo en ocasiones, los sistemas se configuran para que un fallo no produzca daños. por ejemplo, el cliente anterior podía capturar la excepción y limpiarla, aunque sería un tanto torpe. es como limpiar fugas de memoria reiniciando a medianoche. bloqueo basado en el cliente para que integeriterator funcione correctamente con varios subprocesos, cambie el cliente (y los demás) como se indica a continuación: integeriterator iterator = new integeriterator(); while (true) { int nextvalue; synchronized (iterator) { if (!iterator.hasnext()) break; nextvalue = iterator.next(); 416